"use strict";
const STORE="youengineer-wc-grid-v3";
document.head.insertAdjacentHTML("beforeend",'<style>.england-flag{position:relative;overflow:hidden;background:#fff;border:1px solid rgba(255,255,255,.45)}.england-flag:before,.england-flag:after{content:"";position:absolute;background:#cf142b}.england-flag:before{left:0;right:0;top:50%;height:28%;transform:translateY(-50%)}.england-flag:after{top:0;bottom:0;left:50%;width:28%;transform:translateX(-50%)}</style>');
const T={rsa:["South Africa","🇿🇦"],can:["Canada","🇨🇦"],ned:["Netherlands","🇳🇱"],mar:["Morocco","🇲🇦"],ger:["Germany","🇩🇪"],par:["Paraguay","🇵🇾"],fra:["France","🇫🇷"],swe:["Sweden","🇸🇪"],por:["Portugal","🇵🇹"],cro:["Croatia","🇭🇷"],esp:["Spain","🇪🇸"],aut:["Austria","🇦🇹"],usa:["United States","🇺🇸"],bih:["Bosnia and Herzegovina","🇧🇦"],bel:["Belgium","🇧🇪"],sen:["Senegal","🇸🇳"],bra:["Brazil","🇧🇷"],jpn:["Japan","🇯🇵"],civ:["Ivory Coast","🇨🇮"],nor:["Norway","🇳🇴"],mex:["Mexico","🇲🇽"],ecu:["Ecuador","🇪🇨"],eng:["England",""],cod:["DR Congo","🇨🇩"],arg:["Argentina","🇦🇷"],cpv:["Cape Verde","🇨🇻"],aus:["Australia","🇦🇺"],egy:["Egypt","🇪🇬"],sui:["Switzerland","🇨🇭"],dza:["Algeria","🇩🇿"],col:["Colombia","🇨🇴"],gha:["Ghana","🇬🇭"]};
const M=[
["rsa","can","Sun 28 Jun, 20:00","FT",[0,1],"can"],["ned","mar","Tue 30 Jun, 02:00","R32"],["ger","par","Mon 29 Jun, 21:30","R32"],["fra","swe","Tue 30 Jun, 22:00","R32"],
["por","cro","Fri 3 Jul, 00:00","R32"],["esp","aut","Thu 2 Jul, 20:00","R32"],["usa","bih","Thu 2 Jul, 01:00","R32"],["bel","sen","Wed 1 Jul, 21:00","R32"],
["bra","jpn","Mon 29 Jun, 18:00","R32"],["civ","nor","Tue 30 Jun, 18:00","R32"],["mex","ecu","Wed 1 Jul, 02:00","R32"],["eng","cod","Wed 1 Jul, 17:00","R32"],
["arg","cpv","Fri 3 Jul, 23:00","R32"],["aus","egy","Fri 3 Jul, 19:00","R32"],["sui","dza","Fri 3 Jul, 04:00","R32"],["col","gha","Sat 4 Jul, 02:30","R32"]];
const R=[
["round-32","Round of 32",16,M.map(m=>m[2])],
["round-16","Round of 16",8,["Sat 4 Jul, 18:00","Sat 4 Jul, 22:00","Mon 6 Jul, 20:00","Tue 7 Jul, 01:00","Sun 5 Jul, 21:00","Mon 6 Jul, 01:00","Tue 7 Jul, 17:00","Tue 7 Jul, 21:00"]],
["quarter-finals","Quarter-finals",4,["Thu 9 Jul, 21:00","Fri 10 Jul, 20:00","Sat 11 Jul, 22:00","Sun 12 Jul, 02:00"]],
["semi-finals","Semi-finals",2,["Tue 14 Jul, 20:00","Wed 15 Jul, 20:00"]],
["final","Final",1,["Sun 19 Jul, 20:00"]]
];
let picks=load(),pos=[],focus=false;
function key(k){return k&&T[k]?`${T[k][1]} ${T[k][0]}`:""} function load(){try{return JSON.parse(localStorage.getItem(STORE))||{}}catch{return{}}} function save(){localStorage.setItem(STORE,JSON.stringify(picks))}
function team(k){return k&&T[k]?{id:k,name:T[k][0],flag:T[k][1]}:null} function winner(r,i){return r===0&&M[i][5]?M[i][5]:picks[`r${r}m${i}`]||""}
function entrants(r,i){return r===0?[team(M[i][0]),team(M[i][1])]:[team(winner(r-1,i*2)),team(winner(r-1,i*2+1))]}
function clearAfter(r){Object.keys(picks).forEach(k=>{const m=k.match(/^r(\d+)/);if(m&&+m[1]>r)delete picks[k]})}
function pick(r,i,t){if(!t||(r===0&&M[i][5]))return;picks[`r${r}m${i}`]=t.id;clearAfter(r);save();render()}
function css(n,f){const v=parseFloat(getComputedStyle(document.documentElement).getPropertyValue(n));return Number.isFinite(v)?v:f}
function geometry(){const w=css("--card-w",220),h=css("--card-h",130),g=css("--round-gap",16),cg=css("--col-gap",56),p=css("--bracket-pad",12),to=css("--title-offset",38),xs=R.map((_,r)=>p+r*(w+cg));pos=[];pos[0]=M.map((_,i)=>({x:xs[0],y:p+to+i*(h+g)}));for(let r=1;r<R.length;r++){pos[r]=[];for(let i=0;i<R[r][2];i++){const a=pos[r-1][i*2],b=pos[r-1][i*2+1],cy=(a.y+h/2+b.y+h/2)/2;pos[r][i]={x:xs[r],y:cy-h/2}}}return{w,h,p,to,width:p*2+R.length*w+(R.length-1)*cg,height:p*2+to+M.length*h+(M.length-1)*g}}
function a(label,href){const x=document.createElement("a");x.textContent=label;x.href=href;x.target="_blank";x.rel="noopener noreferrer";return x}
function tools(t){const d=document.createElement("div");d.className="team-tools";if(!t)return d;const q=encodeURIComponent(`${t.name} football team World Cup 2026`);d.append(a("News",`https://news.google.com/search?q=${q}`));d.append(a("Wiki",`https://en.wikipedia.org/w/index.php?search=${encodeURIComponent(t.name+" national football team")}`));d.append(a("Images",`https://www.google.com/search?tbm=isch&q=${q}`));return d}
function flag(t){return `<span class="flag ${t.id==="eng"?"england-flag":""}">${t.id==="eng"?"":t.flag}</span>`}
function teamRow(r,i,t,sel,score){const wrap=document.createElement("div"),b=document.createElement("button");b.className="team-button";b.type="button";if(!t){b.disabled=true;b.innerHTML='<span class="flag">◇</span><span class="team-name">TBD</span><span></span>';wrap.append(b);return wrap}const locked=r===0&&M[i][5],s=sel===t.id;if(s)b.classList.add("selected");if(locked){b.classList.add("locked");b.disabled=true}b.innerHTML=`${flag(t)}<span class="team-name">${t.name}</span><span class="pick-indicator">${score!==undefined?score+(s?" ✓":""):(s?"✓":"›")}</span>`;b.onclick=()=>pick(r,i,t);wrap.append(b,tools(t));return wrap}
function card(r,i){const [x,y]=entrants(r,i),sel=winner(r,i),m=document.createElement("article");m.className="match-card";m.style.left=pos[r][i].x+"px";m.style.top=pos[r][i].y+"px";if(r===4)m.classList.add("champion-card");const meta=document.createElement("div");meta.className="match-meta";meta.innerHTML=`<span>${R[r][3][i]||"TBD"}</span><span>${r===0?M[i][3]:"Predict"}</span>`;m.append(meta,teamRow(r,i,x,sel,r===0?M[i][4]?.[0]:undefined),teamRow(r,i,y,sel,r===0?M[i][4]?.[1]:undefined));return m}
function lines(br,g){const s=document.createElementNS("http://www.w3.org/2000/svg","svg");s.classList.add("connector-layer");s.setAttribute("width",g.width);s.setAttribute("height",g.height);s.setAttribute("viewBox",`0 0 ${g.width} ${g.height}`);for(let r=0;r<R.length-1;r++)for(let i=0;i<R[r][2];i++){const m=pos[r][i],n=pos[r+1][Math.floor(i/2)],x1=m.x+g.w,y1=m.y+g.h/2,x2=n.x,y2=n.y+g.h/2,mid=x1+(x2-x1)/2,p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",`M ${x1} ${y1} H ${mid} V ${y2} H ${x2}`);p.setAttribute("class","connector-path");s.append(p)}br.append(s)}
function render(){const wrap=document.querySelector(".bracket-wrap"),br=document.getElementById("bracket"),sl=wrap.scrollLeft,st=wrap.scrollTop,g=geometry();br.innerHTML="";br.style.width=g.width+"px";br.style.height=g.height+"px";lines(br,g);R.forEach((r,ri)=>{const title=document.createElement("h2");title.className="round-title";title.id=r[0];title.dataset.round=r[0];title.textContent=r[1];title.style.left=pos[ri][0].x+"px";title.style.top=g.p+"px";br.append(title);for(let i=0;i<r[2];i++)br.append(card(ri,i))});const champ=team(winner(4,0)),official=M.filter(m=>m[5]).length;document.getElementById("championName").textContent=champ?champ.name:"TBD";document.getElementById("selectionCount").textContent=`${Object.keys(picks).length+official} / 31`;wrap.scrollLeft=sl;wrap.scrollTop=st;nav()}
function nav(){const wrap=document.querySelector(".bracket-wrap"),titles=[...document.querySelectorAll(".round-title")];let active=titles[0]?.dataset.round;titles.forEach(t=>{if(t.offsetLeft-60<=wrap.scrollLeft)active=t.dataset.round});document.querySelectorAll(".round-nav button").forEach(b=>b.classList.toggle("active",b.dataset.round===active))}
function scrollRound(id){const w=document.querySelector(".bracket-wrap"),t=document.getElementById(id);if(t)w.scrollTo({left:Math.max(0,t.offsetLeft-12),behavior:"smooth"})}
function setFocus(v){focus=v;document.body.classList.toggle("focus-mode",v);document.getElementById("fullscreenButton").textContent=v?"Exit":"Fullscreen";setTimeout(render,120)}
document.getElementById("resetButton").onclick=()=>{picks={};save();render()};document.getElementById("fullscreenButton").onclick=async()=>{if(focus){if(document.fullscreenElement&&document.exitFullscreen)await document.exitFullscreen().catch(()=>{});setFocus(false);return}setFocus(true);if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen().catch(()=>{})};document.addEventListener("fullscreenchange",()=>{if(!document.fullscreenElement&&focus)setFocus(false)});document.querySelector(".round-nav").onclick=e=>{const b=e.target.closest("button[data-round]");if(b)scrollRound(b.dataset.round)};document.querySelector(".bracket-wrap").addEventListener("scroll",nav,{passive:true});window.addEventListener("resize",render,{passive:true});render();
