const mythSource = `id|name|category|symbol|summary|story|lesson|tags
medusa|Medusa|Monsters and transformations|🐍|A mortal Gorgon whose image became one of the strongest symbols in Greek myth.|Medusa is remembered for a gaze that could turn people to stone. Perseus defeats her by using reflection, patience and timing rather than charging blindly.|Inspect a difficult problem before acting on it.|Gorgon, Perseus, reflection, courage
athena|Athena|Olympians|🦉|Goddess of wisdom, strategy, craft and disciplined skill.|Athena helps heroes through plans, tools and calm judgement. Her power is intelligence under pressure.|Good engineering is judgement, structure and clarity.|wisdom, strategy, craft, owl
hades|Hades|Underworld|🪙|Ruler of the underworld and guardian of the hidden realm.|Hades is stern and ordered. His kingdom is a place of rules, thresholds, memory and consequence.|Design systems with clear boundaries and protected gates.|underworld, rules, threshold, wealth
persephone|Persephone|Underworld|🌺|Queen of the underworld and figure of seasonal return.|Persephone connects spring growth with the shadowed world below. Her story is often read as a myth of cycles, change and renewal.|Projects have seasons: design, build, rest, review and renew.|seasons, return, underworld, spring
demeter|Demeter|Olympians|🌾|Goddess of grain, harvest and the rhythm of the earth.|Demeter stands for cultivation, patience and the labour behind abundance. Her story gives mythic weight to the changing year.|Small daily improvements become a harvest.|harvest, earth, patience, growth
hecate|Hecate|Underworld|🗝️|Goddess of crossroads, night, thresholds and hidden knowledge.|Hecate appears where paths divide and choices become serious. Torches and keys make her a guide at uncertain crossings.|When code branches, name the paths clearly.|crossroads, keys, night, choices
melinoe|Melinoe|Underworld|🌑|A mysterious underworld figure associated with night and spirits.|Melinoe belongs to later Orphic tradition and suggests a world between light and darkness. She is useful for exploring mystery and layered identity.|Explore contrast in design: visible and hidden, simple and advanced.|night, spirits, mystery, Orphic
chronos|Chronos|Cosmic powers|⏳|Personification of time.|Chronos represents time as a force that measures, changes and reveals. In a clock project, he is the mythic logic behind every second.|Timing bugs become visible every second.|time, clock, cosmos, change
nyx|Nyx|Cosmic powers|🌌|Primordial goddess of night.|Nyx is older than many Olympian stories and represents the deep night from which other powers emerge. Mystery is not emptiness.|A blank screen is a starting point for structure.|night, primordial, mystery, cosmos
hypnos|Hypnos|Cosmic powers|💤|Personification of sleep.|Hypnos shows that rest is a force, not a failure of effort. Even heroes need recovery before judgement returns.|Debugging improves after rest.|sleep, rest, dreams, recovery
thanatos|Thanatos|Cosmic powers|🪽|Personification of peaceful death in Greek myth.|Thanatos marks the boundary of mortal life. He reminds readers that limits give action meaning.|Respect limits in memory, time, scope and attention.|limit, boundary, wings, mortality
nemesis|Nemesis|Cosmic powers|⚖️|Goddess of balance, consequence and measured justice.|Nemesis appears when pride grows beyond proportion. She restores balance where excess becomes dangerous.|Code review checks confidence against evidence.|balance, justice, consequence, measure
the-fates|The Fates|Cosmic powers|🧵|Three figures who spin, measure and cut the thread of life.|Clotho spins, Lachesis measures and Atropos cuts. Together they turn life into a thread with pattern, length and ending.|Create, measure and close tasks cleanly.|thread, destiny, measure, closure
zeus|Zeus|Olympians|⚡|King of the Olympian gods and wielder of the thunderbolt.|Zeus rules from Olympus and is linked with storms, law, hospitality and authority. His stories ask how power should be used.|Admin power needs restraint and accountability.|thunder, authority, Olympus, law
hera|Hera|Olympians|🦚|Queen of Olympus, linked with dignity, status and sovereignty.|Hera is majestic and formidable. Her myths often explore loyalty, rivalry and wounded honour.|A polished interface should have dignity and consistency.|queen, peacock, dignity, Olympus
poseidon|Poseidon|Olympians|🌊|God of the sea, earthquakes and horses.|Poseidon represents restless force: waves, storms, shaking ground and sudden change. Sailors respect him because the sea is never fully controlled.|Build resilient code for changing conditions.|sea, storm, trident, horses
apollo|Apollo|Olympians|☀️|God of light, music, healing, prophecy and order.|Apollo brings clarity and harmony, but also discipline. His oracle at Delphi became a symbol of difficult knowledge.|Readable code is clear, proportioned and tuned.|light, music, prophecy, Delphi
artemis|Artemis|Olympians|🏹|Goddess of the hunt, wild places and independence.|Artemis moves through forests with focus and self-command. She protects boundaries and values freedom.|A good project needs independent modules and clear boundaries.|hunt, moon, wild, bow
hermes|Hermes|Olympians|🪽|Messenger god of travellers, trade, language and clever movement.|Hermes crosses boundaries quickly. He guides travellers, carries messages and turns speed into communication.|APIs carry messages between parts of a system.|messenger, travel, language, speed
aphrodite|Aphrodite|Olympians|🕊️|Goddess of beauty, attraction and desire.|Aphrodite shows that beauty can move people as powerfully as force. In myth, attraction changes the path of kings and heroes.|Visual design matters because people engage with grace.|beauty, dove, attraction, design
hephaestus|Hephaestus|Olympians|⚒️|God of fire, metalwork, invention and the workshop.|Hephaestus makes extraordinary objects through craft, patience and technical skill. His forge is the workshop of Olympus.|Makers win by building useful things.|forge, craft, metalwork, invention
dares|Ares|Olympians|🛡️|God of war and direct conflict.|Ares represents heat, force and confrontation. Greek myth often contrasts him with Athena's disciplined strategy.|Do not attack bugs blindly; use strategy before force.|war, shield, conflict, force
dionysus|Dionysus|Olympians|🍇|God of theatre, wine, masks and transformation.|Dionysus breaks rigid order and reveals hidden emotion. He is linked with performance, surprise and the freedom of theatre.|Creative projects need play and experimentation.|theatre, masks, grapes, transformation
hestia|Hestia|Olympians|🔥|Goddess of the hearth and steady centre.|Hestia is quiet but essential. The hearth is the centre that makes a place ordered and safe.|Every project needs a stable centre: README, structure and purpose.|hearth, home, centre, stability
prometheus|Prometheus|Titans and rebels|🔥|Titan associated with foresight, human craft and stolen fire.|Prometheus brings fire to humanity and becomes a symbol of risky help, invention and defiance. His name suggests thinking ahead.|Technology is powerful, so build with foresight.|fire, foresight, invention, Titan
pandora|Pandora|Titans and rebels|📦|A figure linked with curiosity and the famous jar of troubles.|Pandora opens a container that releases many troubles, yet hope remains. The story turns curiosity into a serious force.|Before importing anything, ask what it may release.|curiosity, hope, jar, consequence
atlas|Atlas|Titans and rebels|🌍|Titan imagined as bearing the heavens.|Atlas stands under an immense burden. His image became a symbol of endurance and responsibility.|Do not let one file carry the whole project.|burden, Titan, heavens, endurance
perseus|Perseus|Heroes|🪞|Hero known for defeating Medusa with reflected sight.|Perseus succeeds by using gifts wisely: a reflective shield, winged sandals and careful planning. The story rewards preparation over panic.|Tools matter when used thoughtfully.|hero, Medusa, mirror, planning
theseus|Theseus|Heroes|🧶|Hero linked with the Labyrinth and the Minotaur.|Theseus enters the Labyrinth and survives by following a thread. The myth turns navigation into the difference between courage and confusion.|Leave a thread through the maze: comments, tests and commits.|Labyrinth, thread, Minotaur, navigation
ariadne|Ariadne|Heroes|🧵|Keeper of the thread that guides Theseus through the Labyrinth.|Ariadne's thread is simple but decisive. It proves that a small guide can make a difficult system understandable.|A clear guide can beat a complex feature.|thread, guide, Labyrinth, clarity
minotaur|The Minotaur|Monsters and transformations|🐂|A bull-headed creature hidden in the Labyrinth.|The Minotaur represents what a society hides at the centre of a maze. The monster is frightening, but the maze is also part of the danger.|Ask whether the bug is the monster or the architecture around it.|Labyrinth, monster, maze, Crete
daedalus|Daedalus|Wisdom and craft|🛠️|Master craftsman, inventor and designer of the Labyrinth.|Daedalus is brilliant, but his inventions carry consequences. His work shows that intelligence without judgement can trap the maker too.|Designers are responsible for the systems they create.|craft, Labyrinth, invention, design
icarus|Icarus|Heroes|🪽|The flyer whose wings became a warning about excess.|Icarus flies with crafted wings but ignores the safe path. His story is not against ambition; it is against ignoring constraints.|Ambition needs testing, limits and humility.|flight, wings, risk, limits
odysseus|Odysseus|Heroes|⛵|Hero of long travel, cunning, endurance and return.|Odysseus faces monsters, temptation, delay and disguise on the journey home. His strength is adaptability.|Long projects need navigation, patience and recovery from detours.|voyage, cunning, return, Ithaca
penelope|Penelope|Heroes|🧶|A figure of patience, intelligence and strategic delay.|Penelope weaves and unweaves while preserving order through uncertainty. Her patience is active, not passive.|Sometimes slow the process until clarity returns.|weaving, patience, strategy, Ithaca
circe|Circe|Monsters and transformations|✨|Enchantress associated with transformation and hidden knowledge.|Circe changes visitors into animals in the Odyssey. Her island tests judgement, identity and self-control.|Interfaces can transform user behaviour, so design ethically.|magic, island, transformation, Odyssey
achilles|Achilles|Trojan cycle|🛡️|The greatest Greek warrior of the Trojan War tradition.|Achilles is almost unbeatable in battle but deeply vulnerable in honour, friendship and fate. His story asks what glory costs.|Strength in one area does not remove vulnerability in another.|Troy, warrior, glory, vulnerability
patroclus|Patroclus|Trojan cycle|🤝|Companion of Achilles and key figure in the Iliad.|Patroclus acts when others hesitate, and his fate changes the direction of the war story. He shows loyalty and consequence.|One action can change a project path.|loyalty, Iliad, friendship, consequence
hector|Hector|Trojan cycle|🏛️|Trojan defender known for duty, courage and family honour.|Hector fights for city, household and obligation. His dignity makes him one of the most human figures in the Trojan story.|Responsibility can be the highest form of courage.|Troy, duty, defender, honour
helen|Helen|Trojan cycle|🌟|A figure whose beauty becomes tied to the Trojan War tradition.|Helen's story is surrounded by questions of choice, blame, beauty and consequence. She is more than a symbol in a world of power.|Avoid reducing complex people or problems to one label.|Troy, beauty, complexity, war
paris|Paris|Trojan cycle|🍎|Trojan prince linked with the judgement of the golden apple.|Paris chooses between divine promises, and his judgement becomes a spark in a larger conflict. The myth shows how incentives shape choices.|Decision-making matters because incentives shape outcomes.|Troy, apple, choice, consequence
cassandra|Cassandra|Trojan cycle|🔮|Prophetess of Troy whose warnings are not believed.|Cassandra sees danger clearly but cannot persuade others. Her tragedy is lack of trust from the audience, not lack of insight.|Data is not enough; communication and credibility matter.|prophecy, Troy, warning, trust
orpheus|Orpheus|Journeys and transformations|🎵|Musician whose song could move nature and the underworld.|Orpheus journeys below to recover Eurydice, relying on music rather than weapons. Art becomes a force that can open impossible doors.|Skill and beauty can persuade where force fails.|music, underworld, journey, art
eurydice|Eurydice|Journeys and transformations|🌿|The lost beloved at the centre of Orpheus's underworld journey.|Eurydice is often quiet in the surviving story, yet everything turns around her absence and possible return. She gives the myth emotional gravity.|What is missing can shape a system as strongly as what is present.|underworld, return, loss, Orpheus
heracles|Heracles|Heroes|🦁|Hero known for strength, endurance and the Twelve Labours.|Heracles faces tasks that require more than muscle: courage, persistence, help and planning. His labours make huge work divisible.|Large projects become possible when broken into labours.|labours, strength, lion, endurance
atalanta|Atalanta|Heroes|🏃|Swift huntress and athlete known for speed and independence.|Atalanta outruns expectations as much as opponents. Her stories emphasise skill, discipline and refusal to be underestimated.|Performance comes from training and focus.|speed, huntress, race, skill
jason|Jason|Voyages|🐏|Leader of the Argonauts in the quest for the Golden Fleece.|Jason's quest depends on a crew, a ship and help from others. The voyage reminds us that heroic work can be collaborative.|Repositories are ships; structure them for a crew.|Argonauts, fleece, ship, quest
medea|Medea|Journeys and transformations|🧪|A powerful sorceress whose story explores intelligence, exile and dangerous anger.|Medea is one of the most intense figures in Greek drama. She combines brilliance, injury and destructive resolve.|Powerful knowledge needs ethical control.|magic, exile, drama, power
sisyphus|Sisyphus|Underworld|🪨|A clever king condemned to roll a stone forever.|Sisyphus is punished with a task that repeats without completion. His story became a symbol of pointless labour and stubborn endurance.|Automate repeated work; do not roll the same stone by hand.|stone, repetition, underworld, automation
tantalus|Tantalus|Underworld|🍎|A punished figure surrounded by things he cannot reach.|Tantalus stands near food and water that always withdraw. The myth gives us the word tantalise: desire without access.|Do not promise interface actions that cannot work.|desire, punishment, access, underworld
narcissus|Narcissus|Journeys and transformations|🌼|A youth associated with reflection and self-absorption.|Narcissus becomes fixed on his own reflection and cannot turn outward. Looking is not the same as understanding.|Build for users and feedback, not self-admiration.|reflection, flower, self, warning
echo|Echo|Journeys and transformations|🔁|A nymph linked with repeated speech.|Echo can only repeat what she hears. Her myth turns voice, repetition and silence into a memorable transformation.|Do not only echo code; understand it, then improve it.|voice, repetition, nymph, sound
arachne|Arachne|Wisdom and craft|🕸️|A brilliant weaver whose contest with Athena becomes a transformation myth.|Arachne is gifted and proud. Her story explores talent, rivalry and the danger of skill without humility.|Skill grows stronger with respect and teachability.|weaving, craft, Athena, humility
pygmalion|Pygmalion|Wisdom and craft|🗿|A sculptor whose artwork becomes central to a myth of creation.|Pygmalion creates an image so beautiful that the boundary between art and life becomes the question. It is a story about makers and values.|Creators should ask what values they build into their work.|sculpture, art, creation, maker
eros-and-psyche|Eros and Psyche|Journeys and transformations|🦋|A story of trust, tasks and the soul's journey.|Psyche must complete difficult tasks and learn trust after doubt breaks a hidden agreement. Her name became linked with soul and mind.|Complex goals need perseverance, help and repaired trust.|soul, trust, tasks, butterfly
the-muses|The Muses|Wisdom and craft|🎭|Nine goddesses of inspiration, memory and the arts.|The Muses preside over song, history, dance, poetry, astronomy and more. They show that knowledge and creativity belong together.|A good project can combine code, story, design and memory.|arts, inspiration, memory, learning
the-sirens|The Sirens|Monsters and transformations|🎼|Singers whose voices lure sailors from the safe route.|The Sirens offer irresistible sound and dangerous distraction. Odysseus survives by planning how to hear without being destroyed.|Build safeguards against distraction before it arrives.|song, sea, Odyssey, temptation
cerberus|Cerberus|Underworld|🐕|The many-headed hound guarding the entrance to the underworld.|Cerberus marks the boundary between the living world and the realm below. He is a guardian, not just a monster.|Access control matters; guard important gates.|guardian, underworld, hound, boundary
charon|Charon|Underworld|⛴️|The ferryman who carries souls across the river of the dead.|Charon moves travellers across a threshold that cannot be crossed casually. The coin for passage makes transition part of the ritual.|Every system needs clear handoff points.|ferry, river, transition, underworld
the-furies|The Furies|Underworld|🔥|Ancient powers of pursuit, guilt and moral consequence.|The Furies hunt wrongdoing that cannot be ignored. In later stories they can become balanced guardians of justice.|Good systems surface unresolved errors instead of hiding them.|justice, pursuit, order, consequence
pegasus|Pegasus|Monsters and transformations|🐎|The winged horse linked with inspiration and heroic flight.|Pegasus rises into stories of heroes, springs and skyward movement. The image suggests power made graceful.|A good feature should feel powerful but light to use.|horse, wings, flight, inspiration
chimera|The Chimera|Monsters and transformations|🐐|A hybrid monster made of several creatures in one form.|The Chimera combines parts that do not naturally belong together. It is dangerous partly because it is difficult to classify.|Beware tangled code that mixes too many responsibilities.|hybrid, monster, classification, Bellerophon
hydra|The Hydra|Monsters and transformations|🐉|A many-headed creature fought by Heracles.|When one head is cut, more can appear. The Hydra is the perfect myth for problems that multiply when attacked carelessly.|Fix root causes, not only visible symptoms.|Heracles, heads, root cause, labour
scylla|Scylla|Monsters and transformations|🪨|A sea monster who makes narrow passage dangerous.|Scylla waits beside a strait where sailors must choose between hazards. She represents unavoidable trade-offs.|Some designs require choosing the least harmful constraint.|sea, Odyssey, strait, tradeoff
charybdis|Charybdis|Monsters and transformations|🌀|A whirlpool monster opposite Scylla in the Odyssey.|Charybdis swallows the sea and makes navigation terrifying. With Scylla, she creates the image of being trapped between two dangers.|Name competing risks clearly before choosing a path.|whirlpool, sea, risk, Odyssey
bellerophon|Bellerophon|Heroes|🐎|Hero associated with Pegasus and the Chimera.|Bellerophon defeats the Chimera with the help of Pegasus, but later overreaches. The story joins skill, assistance and pride.|Success should increase discipline, not arrogance.|Pegasus, Chimera, hero, pride
daphne|Daphne|Journeys and transformations|🌿|A nymph transformed into a laurel tree.|Daphne becomes associated with the laurel, later a symbol of victory and poetic honour. Her transformation links escape, nature and memory.|Symbols can carry stories long after the event.|laurel, tree, transformation, symbol
niobe|Niobe|Journeys and transformations|💧|A queen whose pride before the gods becomes a grief myth.|Niobe boasts beyond measure and is brought into sorrow. Her weeping image became a warning against pride without humility.|Confidence must stay proportionate to reality.|pride, grief, measure, warning
selene|Selene|Cosmic powers|🌙|Moon goddess who drives across the night sky.|Selene represents the visible moon as a divine presence. Her path across the sky makes night feel ordered and luminous.|Good design can make dark parts of a system navigable.|moon, night, sky, light
helios|Helios|Cosmic powers|☀️|Sun god who drives his chariot across the sky.|Helios sees much from above because his daily course crosses the world. He represents observation and exposure.|Logging and monitoring are the sunlight of a project.|sun, chariot, observation, sky
phaethon|Phaethon|Journeys and transformations|☄️|The reckless driver of the sun chariot.|Phaethon tries to control a power beyond his readiness. The story warns that access without preparation can cause disaster.|Do not give production access before training and safeguards.|sun, chariot, risk, readiness`;

window.GREEK_MYTHS = mythSource
  .trim()
  .split("\n")
  .slice(1)
  .map((line) => {
    const [id, name, category, symbol, summary, story, lesson, tags = ""] = line.split("|");
    return {
      id,
      name,
      category,
      symbol,
      summary,
      story,
      lesson,
      tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean)
    };
  });
