"use strict";

window.CIVILISATION_ATLAS_CONFIG = {
  defaultCenter: [15, 18],
  defaultZoomLabel: "world",
  projection: "equirectangular",
  datasetName: "Civilisation Atlas Starter Dataset",
  datasetNote: "Curated educational starter dataset. Not an official complete world heritage register."
};

const atlasSites = [
  { id: "acropolis-athens", name: "Acropolis of Athens", civilisation: "Ancient Greek", region: "Europe", period: "5th century BCE", layer: "heritage", unesco: true, coordinates: [23.726, 37.971], summary: "A hilltop sanctuary and civic symbol of classical Athens.", quest: "Compare architecture, democracy and mythology in one place." },
  { id: "delphi", name: "Delphi", civilisation: "Ancient Greek", region: "Europe", period: "Archaic to Roman", layer: "heritage", unesco: true, coordinates: [22.501, 38.482], summary: "A sacred Greek sanctuary associated with Apollo and the oracle.", quest: "Ask why people travelled for prophecy before making decisions." },
  { id: "olympia", name: "Olympia", civilisation: "Ancient Greek", region: "Europe", period: "Archaic to Roman", layer: "heritage", unesco: true, coordinates: [21.63, 37.637], summary: "The sanctuary linked with the ancient Olympic Games.", quest: "Trace how sport, ritual and reputation became connected." },
  { id: "knossos", name: "Knossos", civilisation: "Minoan", region: "Europe", period: "Bronze Age", layer: "classical", unesco: false, coordinates: [25.163, 35.298], summary: "A major Minoan palace site on Crete.", quest: "Look for palace planning, storage, art and mythic labyrinth ideas." },
  { id: "mycenae", name: "Mycenae", civilisation: "Mycenaean Greek", region: "Europe", period: "Bronze Age", layer: "heritage", unesco: true, coordinates: [22.754, 37.73], summary: "A fortified centre associated with Bronze Age Greece.", quest: "Study gates, walls and power before classical Athens." },
  { id: "troy", name: "Troy", civilisation: "Anatolian and Aegean", region: "Europe and Anatolia", period: "Bronze Age to Roman", layer: "heritage", unesco: true, coordinates: [26.238, 39.957], summary: "A layered archaeological site linked with the Trojan cycle.", quest: "Separate archaeology, poetry and later storytelling." },
  { id: "ephesus", name: "Ephesus", civilisation: "Greek and Roman", region: "Anatolia", period: "Classical to Roman", layer: "heritage", unesco: true, coordinates: [27.34, 37.941], summary: "A major ancient city with Greek, Roman and early Christian layers.", quest: "Identify how a port city becomes a knowledge city." },
  { id: "hattusa", name: "Hattusa", civilisation: "Hittite", region: "Anatolia", period: "Bronze Age", layer: "heritage", unesco: true, coordinates: [34.617, 40.021], summary: "The capital of the Hittite empire in central Anatolia.", quest: "Study fortifications, archives and imperial diplomacy." },
  { id: "gobekli-tepe", name: "Gobekli Tepe", civilisation: "Prehistoric Anatolia", region: "Anatolia", period: "Neolithic", layer: "heritage", unesco: true, coordinates: [38.923, 37.223], summary: "A prehistoric monumental site that changes how students think about early ritual.", quest: "Ask whether temples came before cities." },
  { id: "catalhoyuk", name: "Catalhoyuk", civilisation: "Neolithic Anatolia", region: "Anatolia", period: "Neolithic", layer: "heritage", unesco: true, coordinates: [32.826, 37.667], summary: "A dense early settlement with distinctive houses and wall art.", quest: "Compare village life with later palace and city systems." },

  { id: "colosseum", name: "Colosseum", civilisation: "Roman", region: "Europe", period: "1st century CE", layer: "heritage", unesco: true, coordinates: [12.492, 41.89], summary: "A monumental amphitheatre in ancient Rome.", quest: "Discuss spectacle, engineering and public power." },
  { id: "pompeii", name: "Pompeii", civilisation: "Roman", region: "Europe", period: "1st century CE", layer: "heritage", unesco: true, coordinates: [14.486, 40.749], summary: "A Roman city preserved by the eruption of Vesuvius.", quest: "Use the site as a frozen interface into daily life." },
  { id: "stonehenge", name: "Stonehenge", civilisation: "Neolithic Britain", region: "Europe", period: "Neolithic to Bronze Age", layer: "heritage", unesco: true, coordinates: [-1.826, 51.179], summary: "A prehistoric stone circle in southern Britain.", quest: "Ask how alignment, ritual and labour can be inferred." },
  { id: "skara-brae", name: "Skara Brae", civilisation: "Neolithic Britain", region: "Europe", period: "Neolithic", layer: "heritage", unesco: true, coordinates: [-3.341, 59.049], summary: "A preserved stone-built Neolithic settlement in Orkney.", quest: "Compare domestic architecture with monuments." },
  { id: "newgrange", name: "Newgrange", civilisation: "Neolithic Ireland", region: "Europe", period: "Neolithic", layer: "heritage", unesco: true, coordinates: [-6.475, 53.694], summary: "A passage tomb famous for winter solstice alignment.", quest: "Explore how timekeeping can be built into architecture." },
  { id: "lascaux", name: "Lascaux", civilisation: "Palaeolithic Europe", region: "Europe", period: "Palaeolithic", layer: "heritage", unesco: true, coordinates: [1.17, 45.053], summary: "A cave art site associated with Ice Age image-making.", quest: "Ask what art can reveal before writing exists." },
  { id: "altamira", name: "Altamira", civilisation: "Palaeolithic Europe", region: "Europe", period: "Palaeolithic", layer: "heritage", unesco: true, coordinates: [-4.116, 43.377], summary: "A major prehistoric cave art site in northern Spain.", quest: "Compare natural cave forms with painted figures." },
  { id: "malta-temples", name: "Megalithic Temples of Malta", civilisation: "Neolithic Malta", region: "Europe", period: "Neolithic", layer: "heritage", unesco: true, coordinates: [14.27, 35.827], summary: "A group of prehistoric temple sites on Malta.", quest: "Study monumentality on small islands." },
  { id: "carnac-stones", name: "Carnac Stones", civilisation: "Neolithic Europe", region: "Europe", period: "Neolithic", layer: "classical", unesco: false, coordinates: [-3.082, 47.592], summary: "Large alignments of standing stones in Brittany.", quest: "Map pattern, alignment and uncertainty." },

  { id: "carthage", name: "Carthage", civilisation: "Phoenician and Punic", region: "North Africa", period: "1st millennium BCE", layer: "heritage", unesco: true, coordinates: [10.323, 36.852], summary: "A major Punic and later Roman city on the North African coast.", quest: "Compare maritime trade networks with land empires." },
  { id: "leptis-magna", name: "Leptis Magna", civilisation: "Roman Africa", region: "North Africa", period: "Roman", layer: "heritage", unesco: true, coordinates: [14.293, 32.638], summary: "A Roman city in present-day Libya with major public architecture.", quest: "Ask how empire reshapes local urban identity." },
  { id: "volubilis", name: "Volubilis", civilisation: "Roman Mauretania", region: "North Africa", period: "Roman", layer: "heritage", unesco: true, coordinates: [-5.555, 34.071], summary: "A Roman archaeological site in Morocco.", quest: "Trace the edge of empire on a map." },
  { id: "giza", name: "Giza Pyramid Complex", civilisation: "Ancient Egyptian", region: "North Africa", period: "Old Kingdom", layer: "heritage", unesco: true, coordinates: [31.132, 29.979], summary: "Pyramids, temples and necropolis structures near Cairo.", quest: "Measure how architecture expresses belief and administration." },
  { id: "karnak", name: "Karnak Temple Complex", civilisation: "Ancient Egyptian", region: "North Africa", period: "Middle Kingdom to Ptolemaic", layer: "heritage", unesco: true, coordinates: [32.657, 25.719], summary: "A vast temple complex near Luxor.", quest: "Follow the layers of kingship, ritual and expansion." },
  { id: "abu-simbel", name: "Abu Simbel", civilisation: "Ancient Egyptian", region: "North Africa", period: "New Kingdom", layer: "heritage", unesco: true, coordinates: [31.625, 22.337], summary: "Rock-cut temples associated with Ramesses II.", quest: "Ask how monuments project power across distance." },
  { id: "meroe", name: "Meroe", civilisation: "Kushite", region: "North Africa", period: "1st millennium BCE to CE", layer: "heritage", unesco: true, coordinates: [33.724, 16.937], summary: "A royal city and pyramid field of the Kingdom of Kush.", quest: "Challenge the assumption that Nile civilisation is only Egyptian." },
  { id: "axum", name: "Aksum", civilisation: "Aksumite", region: "East Africa", period: "1st millennium CE", layer: "heritage", unesco: true, coordinates: [38.718, 14.13], summary: "A centre of ancient Ethiopian civilisation and monumental stelae.", quest: "Study trade, religion and kingship in the Red Sea world." },
  { id: "lalibela", name: "Rock-Hewn Churches of Lalibela", civilisation: "Medieval Ethiopia", region: "East Africa", period: "12th to 13th century", layer: "heritage", unesco: true, coordinates: [39.047, 12.03], summary: "A group of rock-cut churches in Ethiopia.", quest: "Ask how architecture can be carved rather than built." },
  { id: "great-zimbabwe", name: "Great Zimbabwe", civilisation: "Shona", region: "Southern Africa", period: "11th to 15th century", layer: "heritage", unesco: true, coordinates: [30.933, -20.267], summary: "A major stone-built city of southern Africa.", quest: "Explore trade, stonework and state formation beyond stereotypes." },
  { id: "timbuktu", name: "Timbuktu", civilisation: "Mali and Songhai", region: "West Africa", period: "Medieval", layer: "heritage", unesco: true, coordinates: [-3.003, 16.766], summary: "A historic centre of learning and trans-Saharan exchange.", quest: "Discuss libraries, manuscripts and desert trade routes." },
  { id: "djenne", name: "Djenne", civilisation: "West African Sahel", region: "West Africa", period: "Medieval to early modern", layer: "heritage", unesco: true, coordinates: [-4.556, 13.906], summary: "A historic town associated with earthen architecture.", quest: "Compare mud architecture with stone architecture." },

  { id: "petra", name: "Petra", civilisation: "Nabataean", region: "Middle East", period: "Classical", layer: "heritage", unesco: true, coordinates: [35.444, 30.328], summary: "A rock-cut city and caravan hub in Jordan.", quest: "Study water engineering and trade geography." },
  { id: "jerash", name: "Jerash", civilisation: "Roman Near East", region: "Middle East", period: "Roman", layer: "classical", unesco: false, coordinates: [35.891, 32.28], summary: "A major Roman city site in Jordan.", quest: "Compare city grids, theatres and colonnaded streets." },
  { id: "persepolis", name: "Persepolis", civilisation: "Achaemenid Persian", region: "Middle East", period: "6th to 4th century BCE", layer: "heritage", unesco: true, coordinates: [52.891, 29.935], summary: "A ceremonial capital of the Achaemenid Empire.", quest: "Read empire through stairways, reliefs and tribute scenes." },
  { id: "pasargadae", name: "Pasargadae", civilisation: "Achaemenid Persian", region: "Middle East", period: "6th century BCE", layer: "heritage", unesco: true, coordinates: [53.167, 30.193], summary: "An early Achaemenid capital associated with Cyrus the Great.", quest: "Compare founding capitals with later imperial display." },
  { id: "babylon", name: "Babylon", civilisation: "Mesopotamian", region: "Middle East", period: "2nd to 1st millennium BCE", layer: "heritage", unesco: true, coordinates: [44.42, 32.536], summary: "A major Mesopotamian city in present-day Iraq.", quest: "Track how a city becomes a symbol in later cultures." },
  { id: "ur", name: "Ziggurat of Ur", civilisation: "Sumerian", region: "Middle East", period: "Bronze Age", layer: "classical", unesco: false, coordinates: [46.103, 30.963], summary: "A monumental ziggurat associated with the city of Ur.", quest: "Compare stepped sacred architecture with pyramids." },
  { id: "nineveh", name: "Nineveh", civilisation: "Assyrian", region: "Middle East", period: "Neo-Assyrian", layer: "classical", unesco: false, coordinates: [43.155, 36.36], summary: "A major Assyrian capital near modern Mosul.", quest: "Ask how walls, palaces and libraries express state power." },
  { id: "samarkand", name: "Samarkand", civilisation: "Silk Road", region: "Central Asia", period: "Ancient to Timurid", layer: "heritage", unesco: true, coordinates: [66.975, 39.654], summary: "A major Silk Road city in Uzbekistan.", quest: "Map how routes create cosmopolitan cities." },
  { id: "bukhara", name: "Bukhara", civilisation: "Silk Road", region: "Central Asia", period: "Ancient to Islamic", layer: "heritage", unesco: true, coordinates: [64.423, 39.774], summary: "A historic city on Central Asian trade routes.", quest: "Study continuity across religions, empires and markets." },
  { id: "merv", name: "Merv", civilisation: "Silk Road", region: "Central Asia", period: "Ancient to medieval", layer: "heritage", unesco: true, coordinates: [62.178, 37.664], summary: "A major oasis city in Turkmenistan.", quest: "Ask why oasis geography matters to global history." },

  { id: "mohenjo-daro", name: "Mohenjo-daro", civilisation: "Indus Valley", region: "South Asia", period: "Bronze Age", layer: "heritage", unesco: true, coordinates: [68.138, 27.324], summary: "A major urban centre of the Indus Valley civilisation.", quest: "Look for drainage, planning and civic engineering." },
  { id: "harappa", name: "Harappa", civilisation: "Indus Valley", region: "South Asia", period: "Bronze Age", layer: "classical", unesco: false, coordinates: [72.865, 30.629], summary: "A major Indus Valley city site in Punjab.", quest: "Compare city planning with Mohenjo-daro." },
  { id: "lothal", name: "Lothal", civilisation: "Indus Valley", region: "South Asia", period: "Bronze Age", layer: "classical", unesco: false, coordinates: [72.249, 22.522], summary: "An Indus Valley site associated with trade and dock-like structures.", quest: "Explore maritime trade as part of Bronze Age urbanism." },
  { id: "sanchi", name: "Sanchi", civilisation: "Mauryan and Buddhist", region: "South Asia", period: "3rd century BCE onward", layer: "heritage", unesco: true, coordinates: [77.739, 23.48], summary: "A Buddhist stupa complex in India.", quest: "Read symbols, gateways and pilgrimage routes." },
  { id: "ajanta", name: "Ajanta Caves", civilisation: "Indian Buddhist", region: "South Asia", period: "2nd century BCE to 6th century CE", layer: "heritage", unesco: true, coordinates: [75.703, 20.552], summary: "Rock-cut Buddhist caves with paintings and sculpture.", quest: "Compare narrative art with architecture." },
  { id: "ellora", name: "Ellora Caves", civilisation: "Indian Buddhist, Hindu and Jain", region: "South Asia", period: "6th to 10th century", layer: "heritage", unesco: true, coordinates: [75.179, 20.026], summary: "Rock-cut caves representing multiple religious traditions.", quest: "Study coexistence through spatial design." },
  { id: "anuradhapura", name: "Anuradhapura", civilisation: "Ancient Sri Lankan", region: "South Asia", period: "Ancient to medieval", layer: "heritage", unesco: true, coordinates: [80.403, 8.312], summary: "An ancient capital of Sri Lanka with major Buddhist monuments.", quest: "Compare reservoirs, monasteries and city planning." },
  { id: "sigiriya", name: "Sigiriya", civilisation: "Ancient Sri Lankan", region: "South Asia", period: "5th century CE", layer: "heritage", unesco: true, coordinates: [80.761, 7.957], summary: "A rock fortress and palace landscape in Sri Lanka.", quest: "Ask how geography can become architecture." },
  { id: "lumbini", name: "Lumbini", civilisation: "Buddhist heritage", region: "South Asia", period: "Ancient", layer: "heritage", unesco: true, coordinates: [83.276, 27.469], summary: "A sacred site associated with the birth of the Buddha.", quest: "Discuss how sacred geography shapes travel." },

  { id: "bagan", name: "Bagan", civilisation: "Burmese", region: "Southeast Asia", period: "9th to 13th century", layer: "heritage", unesco: true, coordinates: [94.867, 21.171], summary: "A landscape of temples and stupas in Myanmar.", quest: "Use density of monuments to think about devotion and state power." },
  { id: "angkor-wat", name: "Angkor Wat", civilisation: "Khmer", region: "Southeast Asia", period: "12th century", layer: "heritage", unesco: true, coordinates: [103.867, 13.412], summary: "A monumental temple complex in Cambodia.", quest: "Study water, kingship and cosmic architecture." },
  { id: "borobudur", name: "Borobudur", civilisation: "Javanese Buddhist", region: "Southeast Asia", period: "8th to 9th century", layer: "heritage", unesco: true, coordinates: [110.203, -7.607], summary: "A vast Buddhist monument in Java.", quest: "Walk the monument as a diagram of spiritual ascent." },
  { id: "prambanan", name: "Prambanan", civilisation: "Javanese Hindu", region: "Southeast Asia", period: "9th century", layer: "heritage", unesco: true, coordinates: [110.492, -7.752], summary: "A major Hindu temple complex in Java.", quest: "Compare temple forms across Buddhist and Hindu sites." },
  { id: "ayutthaya", name: "Ayutthaya", civilisation: "Siamese", region: "Southeast Asia", period: "14th to 18th century", layer: "heritage", unesco: true, coordinates: [100.569, 14.355], summary: "A historic capital city in Thailand.", quest: "Track river geography and royal urbanism." },
  { id: "sukhothai", name: "Sukhothai", civilisation: "Thai", region: "Southeast Asia", period: "13th to 15th century", layer: "heritage", unesco: true, coordinates: [99.789, 17.019], summary: "A historic Thai city and early kingdom centre.", quest: "Compare city layout with religious landscapes." },
  { id: "my-son", name: "My Son Sanctuary", civilisation: "Cham", region: "Southeast Asia", period: "4th to 13th century", layer: "heritage", unesco: true, coordinates: [108.573, 15.765], summary: "A Hindu temple complex of the Cham civilisation in Vietnam.", quest: "Study cultural exchange across the South China Sea." },
  { id: "hue", name: "Complex of Hue Monuments", civilisation: "Vietnamese imperial", region: "Southeast Asia", period: "19th century", layer: "heritage", unesco: true, coordinates: [107.577, 16.469], summary: "An imperial capital complex in Vietnam.", quest: "Compare royal planning across Asia." },

  { id: "great-wall", name: "Great Wall at Badaling", civilisation: "Chinese", region: "East Asia", period: "Ming and earlier", layer: "heritage", unesco: true, coordinates: [116.016, 40.356], summary: "A famous section of the Great Wall of China.", quest: "Ask how borders become architecture." },
  { id: "terracotta-army", name: "Terracotta Army", civilisation: "Qin Chinese", region: "East Asia", period: "3rd century BCE", layer: "heritage", unesco: true, coordinates: [109.278, 34.385], summary: "A vast funerary army associated with the first Qin emperor.", quest: "Discuss scale, standardisation and imperial afterlife." },
  { id: "forbidden-city", name: "Forbidden City", civilisation: "Imperial Chinese", region: "East Asia", period: "Ming to Qing", layer: "heritage", unesco: true, coordinates: [116.397, 39.916], summary: "The imperial palace complex at the centre of Beijing.", quest: "Read power through gates, axes and courtyards." },
  { id: "mogao-caves", name: "Mogao Caves", civilisation: "Silk Road Buddhist", region: "East Asia", period: "4th to 14th century", layer: "heritage", unesco: true, coordinates: [94.81, 40.037], summary: "A Buddhist cave complex near Dunhuang.", quest: "Trace art, trade and religion along desert routes." },
  { id: "nara", name: "Historic Nara", civilisation: "Japanese", region: "East Asia", period: "8th century", layer: "heritage", unesco: true, coordinates: [135.839, 34.689], summary: "Historic monuments of ancient Nara in Japan.", quest: "Compare capital planning and temple landscapes." },
  { id: "kyoto", name: "Historic Kyoto", civilisation: "Japanese", region: "East Asia", period: "Heian to Edo", layer: "heritage", unesco: true, coordinates: [135.785, 34.994], summary: "A historic city of temples, gardens and imperial memory.", quest: "Use the city as a case study in layered cultural design." },
  { id: "gyeongju", name: "Gyeongju", civilisation: "Silla Korean", region: "East Asia", period: "1st millennium CE", layer: "heritage", unesco: true, coordinates: [129.214, 35.835], summary: "A historic capital landscape of the Silla kingdom.", quest: "Study tombs, temples and dynastic memory." },

  { id: "chichen-itza", name: "Chichen Itza", civilisation: "Maya", region: "Mesoamerica", period: "Classic to Postclassic", layer: "heritage", unesco: true, coordinates: [-88.568, 20.684], summary: "A major Maya site in Yucatan.", quest: "Compare astronomy, ritual and political theatre." },
  { id: "teotihuacan", name: "Teotihuacan", civilisation: "Teotihuacan", region: "Mesoamerica", period: "1st millennium CE", layer: "heritage", unesco: true, coordinates: [-98.839, 19.692], summary: "A vast planned city near modern Mexico City.", quest: "Study urban axes and monumental scale." },
  { id: "tikal", name: "Tikal", civilisation: "Maya", region: "Mesoamerica", period: "Classic Maya", layer: "heritage", unesco: true, coordinates: [-89.623, 17.222], summary: "A major Maya city in Guatemala.", quest: "Ask how forest, astronomy and kingship interact." },
  { id: "palenque", name: "Palenque", civilisation: "Maya", region: "Mesoamerica", period: "Classic Maya", layer: "heritage", unesco: true, coordinates: [-92.045, 17.484], summary: "A Maya city famous for architecture and inscriptions.", quest: "Use writing to connect rulers, buildings and dates." },
  { id: "copan", name: "Copan", civilisation: "Maya", region: "Mesoamerica", period: "Classic Maya", layer: "heritage", unesco: true, coordinates: [-89.141, 14.839], summary: "A Maya city in Honduras with notable stelae and stairways.", quest: "Read carved monuments as public data storage." },
  { id: "monte-alban", name: "Monte Alban", civilisation: "Zapotec", region: "Mesoamerica", period: "Preclassic to Classic", layer: "heritage", unesco: true, coordinates: [-96.767, 17.044], summary: "A hilltop Zapotec city in Oaxaca.", quest: "Ask why capitals are placed on high ground." },
  { id: "templo-mayor", name: "Templo Mayor", civilisation: "Aztec", region: "Mesoamerica", period: "Late Postclassic", layer: "classical", unesco: false, coordinates: [-99.132, 19.434], summary: "The ritual centre of Mexica Tenochtitlan in Mexico City.", quest: "Study how one city can sit beneath another." },

  { id: "machu-picchu", name: "Machu Picchu", civilisation: "Inca", region: "Andes", period: "15th century", layer: "heritage", unesco: true, coordinates: [-72.545, -13.163], summary: "An Inca mountain site in Peru.", quest: "Ask how terrain, water and ritual shape architecture." },
  { id: "nazca-lines", name: "Nazca Lines", civilisation: "Nazca", region: "Andes", period: "1st millennium CE", layer: "heritage", unesco: true, coordinates: [-75.133, -14.739], summary: "Large geoglyphs in the desert of southern Peru.", quest: "Discuss scale, visibility and interpretation." },
  { id: "chan-chan", name: "Chan Chan", civilisation: "Chimu", region: "Andes", period: "9th to 15th century", layer: "heritage", unesco: true, coordinates: [-79.074, -8.111], summary: "A large adobe city on the north coast of Peru.", quest: "Compare earthen urbanism in dry climates." },
  { id: "caral", name: "Caral", civilisation: "Norte Chico", region: "Andes", period: "3rd millennium BCE", layer: "heritage", unesco: true, coordinates: [-77.523, -10.893], summary: "One of the oldest urban centres in the Americas.", quest: "Ask what makes a city before pottery or empire." },
  { id: "tiwanaku", name: "Tiwanaku", civilisation: "Tiwanaku", region: "Andes", period: "1st millennium CE", layer: "heritage", unesco: true, coordinates: [-68.673, -16.554], summary: "A high-altitude ceremonial and urban centre near Lake Titicaca.", quest: "Study altitude, agriculture and ritual landscape." },
  { id: "rapa-nui", name: "Rapa Nui", civilisation: "Polynesian", region: "Pacific", period: "Medieval to early modern", layer: "heritage", unesco: true, coordinates: [-109.349, -27.125], summary: "An island landscape famous for moai statues.", quest: "Ask how isolation changes engineering and memory." },
  { id: "cahokia", name: "Cahokia", civilisation: "Mississippian", region: "North America", period: "11th to 14th century", layer: "heritage", unesco: true, coordinates: [-90.062, 38.655], summary: "A major pre-Columbian mound city near the Mississippi.", quest: "Compare earthworks with stone monuments." },
  { id: "mesa-verde", name: "Mesa Verde", civilisation: "Ancestral Puebloan", region: "North America", period: "6th to 13th century", layer: "heritage", unesco: true, coordinates: [-108.462, 37.23], summary: "Cliff dwellings and mesa-top sites in the American Southwest.", quest: "Ask how architecture adapts to rock, climate and defence." },
  { id: "chaco-canyon", name: "Chaco Canyon", civilisation: "Ancestral Puebloan", region: "North America", period: "9th to 12th century", layer: "heritage", unesco: true, coordinates: [-107.956, 36.06], summary: "A monumental canyon landscape in New Mexico.", quest: "Explore roads, astronomy and regional coordination." },
  { id: "lanse-aux-meadows", name: "L'Anse aux Meadows", civilisation: "Norse", region: "North America", period: "11th century", layer: "heritage", unesco: true, coordinates: [-55.533, 51.595], summary: "A Norse site in Newfoundland.", quest: "Use it to discuss contact, navigation and archaeological proof." }
];

window.ATLAS_GEOJSON = {
  type: "FeatureCollection",
  features: atlasSites.map((site) => ({
    type: "Feature",
    geometry: {
      type: "Point",
      coordinates: site.coordinates
    },
    properties: {
      id: site.id,
      name: site.name,
      civilisation: site.civilisation,
      region: site.region,
      period: site.period,
      layer: site.layer,
      unesco: site.unesco,
      summary: site.summary,
      quest: site.quest
    }
  }))
};

window.ATLAS_ROUTES = [
  { id: "mediterranean", name: "Mediterranean learning route", coordinates: [[-5.555, 34.071], [10.323, 36.852], [12.492, 41.89], [23.726, 37.971], [27.34, 37.941], [35.444, 30.328]] },
  { id: "nile-red-sea", name: "Nile and Red Sea route", coordinates: [[31.132, 29.979], [32.657, 25.719], [31.625, 22.337], [33.724, 16.937], [38.718, 14.13], [39.047, 12.03]] },
  { id: "silk-road", name: "Silk Road learning route", coordinates: [[52.891, 29.935], [62.178, 37.664], [66.975, 39.654], [94.81, 40.037], [109.278, 34.385], [116.397, 39.916]] },
  { id: "south-southeast-asia", name: "South and Southeast Asia route", coordinates: [[68.138, 27.324], [77.739, 23.48], [80.403, 8.312], [94.867, 21.171], [103.867, 13.412], [110.203, -7.607]] },
  { id: "mesoamerica", name: "Mesoamerican learning route", coordinates: [[-99.132, 19.434], [-98.839, 19.692], [-96.767, 17.044], [-92.045, 17.484], [-89.623, 17.222], [-88.568, 20.684]] },
  { id: "andes-pacific", name: "Andes and Pacific route", coordinates: [[-77.523, -10.893], [-79.074, -8.111], [-72.545, -13.163], [-75.133, -14.739], [-68.673, -16.554], [-109.349, -27.125]] }
];
